---
- name: Configure App
  hosts: app
  become: true
  roles:
    - app
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
       default:
        - listen 80
        - server_name "reddit-app"
        - location / {proxy_pass http://127.0.0.1:9292;}
